version: '3.8'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hotel
      - POSTGRES_PASSWORD=hotel
      - POSTGRES_DB=hotel

volumes:
  postgres-db: